spring.application.name=trendyol

#database bilgileri
spring.datasource.url=jdbc:postgresql://localhost:5432/trendyol?currentSchema=trendyol
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

#jwt
jwt.expiration=${JWT_EXPIRATION}
jwt.secret=${JWT_SECRET}

#kimlik bilgileri
app.admin.username=${ADMIN_USERNAME}
app.admin.email=${ADMIN_EMAIL}
app.admin.password=${ADMIN_PASSWORD}
app.seed.enabled=true

#hibernate islemleri
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.default_schema=trendyol
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#pageable/sorting islemleri
spring.data.web.pageable.default-page-size=10
spring.data.web.pageable.max-page-size=50
spring.jpa.properties.hibernate.default_batch_fetch_size=20















